apiVersion: v1
kind: Pod
metadata:
  name: online-inference
  labels:
    app: online-inference
spec:
  containers:
    - image: liliyamakhmutova/online_inference:v2
      name: online-inference
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /healz
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 3
      livenessProbe:
            httpGet:
                path: /healz
                port: 8000            
            initialDelaySeconds: 30
            periodSeconds: 3
