apiVersion: v1
kind: Pod
metadata:
  name: online-inference
  labels:
    app: online-inference
spec:
  containers:
    - image: liliyamakhmutova/online_inference:v1
      name: online-inference
      ports:
        - containerPort: 8000
      resources:
        requests:
            memory: "512Mi"
            cpu: 0.5
        limits:
            memory: "1Gi"
            cpu: 1
